export const product = [
  {
    id: '0',
    image: require('../assets/product/ProductImage8.png'),
    title: 'FS - Nike Air Max 270 React...',
    DiscountPrice: 29943,
    price: 53433,
    discount: 24,
  },
  {
    id: '1',
    image: require('../assets/product/ProductImage2.png'),
    title: 'FS - QUILTED MAXI CROS...',
    DiscountPrice: 29943,
    price: 53433,
    discount: 20,
  },
  {
    id: '2',
    image: require('../assets/product/ProductImage3.png'),
    title: 'FS - Nike Air Max 270 React...',
    DiscountPrice: 29943,
    price: 53433,
    discount: 42,
  },
  {
    id: '3',
    image: require('../assets/product/ProductImage4.png'),
    title: 'FS - QUILTED MAXI CROS...',
    DiscountPrice: 29943,
    price: 53433,
    discount: 10,
  },
  {
    id: '4',
    image: require('../assets/product/ProductImage5.png'),
    title: 'FS - QUILTED MAXI CROS...',
    DiscountPrice: 29943,
    price: 53433,
  },
  {
    id: '5',
    image: require('../assets/product/ProductImage6.png'),
    title: 'FS - Nike Air Max 270 React...',
    DiscountPrice: 29943,
    price: 53433,
  },
  {
    id: '6',
    image: require('../assets/product/ProductImage7.png'),
    title: 'FS - QUILTED MAXI CROS...',
    DiscountPrice: 29943,
    price: 53433,
    discount: 5,
  },
  {
    id: '7',
    image: require('../assets/product/ProductImage1.png'),
    title: 'FS - Nike Air Max 270 React...',
    DiscountPrice: 29943,
    price: 53433,
    discount: 10,
  },
];
